export const COUNTRIES = [
  { code: 'IQ', name: 'Iraq', dialCode: '+964', example: '78XXXXXXXX' },
  { code: 'TR', name: 'Turkey', dialCode: '+90', example: '5XXXXXXXXX' },
  { code: 'AE', name: 'UAE', dialCode: '+971', example: '5XXXXXXXX' },
  { code: 'JO', name: 'Jordan', dialCode: '+962', example: '7XXXXXXXX' },
  { code: 'SA', name: 'Saudi Arabia', dialCode: '+966', example: '5XXXXXXXX' },
  { code: 'DZ', name: 'Algeria', dialCode: '+213', example: 'XXXXXXXXX' },
  { code: 'EG', name: 'Egypt', dialCode: '+20', example: '1XXXXXXXXX' },
  { code: 'LB', name: 'Lebanon', dialCode: '+961', example: 'XXXXXXXX' },
  { code: 'SY', name: 'Syria', dialCode: '+963', example: '9XXXXXXXX' },
  { code: 'QA', name: 'Qatar', dialCode: '+974', example: 'XXXXXXXX' },
  { code: 'KW', name: 'Kuwait', dialCode: '+965', example: 'XXXXXXXX' },
  { code: 'OM', name: 'Oman', dialCode: '+968', example: 'XXXXXXXX' },
  { code: 'BH', name: 'Bahrain', dialCode: '+973', example: 'XXXXXXXX' },
  { code: 'US', name: 'United States', dialCode: '+1', example: 'XXXXXXXXXX' },
  { code: 'GB', name: 'United Kingdom', dialCode: '+44', example: 'XXXXXXXXXX' },
  { code: 'CA', name: 'Canada', dialCode: '+1', example: 'XXXXXXXXXX' },
  { code: 'DE', name: 'Germany', dialCode: '+49', example: 'XXXXXXXXXX' },
  { code: 'FR', name: 'France', dialCode: '+33', example: 'XXXXXXXXXX' },
  { code: 'IT', name: 'Italy', dialCode: '+39', example: 'XXXXXXXXXX' },
  { code: 'ES', name: 'Spain', dialCode: '+34', example: 'XXXXXXXXXX' },
  { code: 'NL', name: 'Netherlands', dialCode: '+31', example: 'XXXXXXXXXX' },
  { code: 'SE', name: 'Sweden', dialCode: '+46', example: 'XXXXXXXXXX' },
  { code: 'NO', name: 'Norway', dialCode: '+47', example: 'XXXXXXXXXX' },
  { code: 'FI', name: 'Finland', dialCode: '+358', example: 'XXXXXXXXXX' },
  { code: 'DK', name: 'Denmark', dialCode: '+45', example: 'XXXXXXXXXX' },
  { code: 'CH', name: 'Switzerland', dialCode: '+41', example: 'XXXXXXXXXX' },
  { code: 'AT', name: 'Austria', dialCode: '+43', example: 'XXXXXXXXXX' },
  { code: 'BE', name: 'Belgium', dialCode: '+32', example: 'XXXXXXXXXX' },
  { code: 'GR', name: 'Greece', dialCode: '+30', example: 'XXXXXXXXXX' },
  { code: 'PT', name: 'Portugal', dialCode: '+351', example: 'XXXXXXXXXX' },
  { code: 'IE', name: 'Ireland', dialCode: '+353', example: 'XXXXXXXXXX' },
  { code: 'RU', name: 'Russia', dialCode: '+7', example: 'XXXXXXXXXX' },
  { code: 'CN', name: 'China', dialCode: '+86', example: 'XXXXXXXXXX' },
  { code: 'JP', name: 'Japan', dialCode: '+81', example: 'XXXXXXXXXX' },
  { code: 'KR', name: 'South Korea', dialCode: '+82', example: 'XXXXXXXXXX' },
  { code: 'IN', name: 'India', dialCode: '+91', example: 'XXXXXXXXXX' },
  { code: 'PK', name: 'Pakistan', dialCode: '+92', example: 'XXXXXXXXXX' },
  { code: 'BD', name: 'Bangladesh', dialCode: '+880', example: 'XXXXXXXXXX' },
  { code: 'ID', name: 'Indonesia', dialCode: '+62', example: 'XXXXXXXXXX' },
  { code: 'MY', name: 'Malaysia', dialCode: '+60', example: 'XXXXXXXXXX' },
  { code: 'TH', name: 'Thailand', dialCode: '+66', example: 'XXXXXXXXXX' },
  { code: 'VN', name: 'Vietnam', dialCode: '+84', example: 'XXXXXXXXXX' },
  { code: 'PH', name: 'Philippines', dialCode: '+63', example: 'XXXXXXXXXX' },
  { code: 'AU', name: 'Australia', dialCode: '+61', example: 'XXXXXXXXXX' },
  { code: 'NZ', name: 'New Zealand', dialCode: '+64', example: 'XXXXXXXXXX' },
  { code: 'BR', name: 'Brazil', dialCode: '+55', example: 'XXXXXXXXXX' },
  { code: 'MX', name: 'Mexico', dialCode: '+52', example: 'XXXXXXXXXX' },
  { code: 'AR', name: 'Argentina', dialCode: '+54', example: 'XXXXXXXXXX' },
  { code: 'CL', name: 'Chile', dialCode: '+56', example: 'XXXXXXXXXX' },
  { code: 'CO', name: 'Colombia', dialCode: '+57', example: 'XXXXXXXXXX' },
  { code: 'ZA', name: 'South Africa', dialCode: '+27', example: 'XXXXXXXXXX' },
  { code: 'NG', name: 'Nigeria', dialCode: '+234', example: 'XXXXXXXXXX' },
  { code: 'LY', name: 'Libya', dialCode: '+218', example: 'XXXXXXXX' },
  { code: 'MA', name: 'Morocco', dialCode: '+212', example: 'XXXXXXXXX' },
  { code: 'TN', name: 'Tunisia', dialCode: '+216', example: 'XXXXXXXX' },
  { code: 'SD', name: 'Sudan', dialCode: '+249', example: 'XXXXXXXXX' },
  { code: 'YE', name: 'Yemen', dialCode: '+967', example: 'XXXXXXXX' },
  // ... adding more to cover "all" as much as practical in a single tool call
  { code: 'AF', name: 'Afghanistan', dialCode: '+93', example: 'XXXXXXXXX' },
  { code: 'AL', name: 'Albania', dialCode: '+355', example: 'XXXXXXXXX' },
  { code: 'AD', name: 'Andorra', dialCode: '+376', example: 'XXXXXX' },
  { code: 'AO', name: 'Angola', dialCode: '+244', example: 'XXXXXXXXX' },
  { code: 'AM', name: 'Armenia', dialCode: '+374', example: 'XXXXXXXX' },
  { code: 'AW', name: 'Aruba', dialCode: '+297', example: 'XXXXXXX' },
  { code: 'AZ', name: 'Azerbaijan', dialCode: '+994', example: 'XXXXXXXXX' },
  { code: 'BS', name: 'Bahamas', dialCode: '+1', example: 'XXXXXXX' },
  { code: 'BB', name: 'Barbados', dialCode: '+1', example: 'XXXXXXX' },
  { code: 'BY', name: 'Belarus', dialCode: '+375', example: 'XXXXXXXXX' },
  { code: 'BZ', name: 'Belize', dialCode: '+501', example: 'XXXXXXX' },
  { code: 'BJ', name: 'Benin', dialCode: '+229', example: 'XXXXXXXX' },
  { code: 'BM', name: 'Bermuda', dialCode: '+1', example: 'XXXXXXX' },
  { code: 'BT', name: 'Bhutan', dialCode: '+975', example: 'XXXXXXXX' },
  { code: 'BO', name: 'Bolivia', dialCode: '+591', example: 'XXXXXXXX' },
  { code: 'BA', name: 'Bosnia and Herzegovina', dialCode: '+387', example: 'XXXXXXXX' },
  { code: 'BW', name: 'Botswana', dialCode: '+267', example: 'XXXXXXXX' },
  { code: 'BN', name: 'Brunei', dialCode: '+673', example: 'XXXXXXX' },
  { code: 'BG', name: 'Bulgaria', dialCode: '+359', example: 'XXXXXXXXX' },
  { code: 'BF', name: 'Burkina Faso', dialCode: '+226', example: 'XXXXXXXX' },
  { code: 'BI', name: 'Burundi', dialCode: '+257', example: 'XXXXXXXX' },
  { code: 'KH', name: 'Cambodia', dialCode: '+855', example: 'XXXXXXXXX' },
  { code: 'CM', name: 'Cameroon', dialCode: '+237', example: 'XXXXXXXXX' },
  { code: 'CV', name: 'Cape Verde', dialCode: '+238', example: 'XXXXXXX' },
  { code: 'CF', name: 'Central African Republic', dialCode: '+236', example: 'XXXXXXXX' },
  { code: 'TD', name: 'Chad', dialCode: '+235', example: 'XXXXXXXX' },
  { code: 'KM', name: 'Comoros', dialCode: '+269', example: 'XXXXXXX' },
  { code: 'CG', name: 'Congo [Republic]', dialCode: '+242', example: 'XXXXXXXXX' },
  { code: 'CD', name: 'Congo [DRC]', dialCode: '+243', example: 'XXXXXXXXX' },
  { code: 'CR', name: 'Costa Rica', dialCode: '+506', example: 'XXXXXXXX' },
  { code: 'HR', name: 'Croatia', dialCode: '+385', example: 'XXXXXXXXX' },
  { code: 'CU', name: 'Cuba', dialCode: '+53', example: 'XXXXXXXX' },
  { code: 'CY', name: 'Cyprus', dialCode: '+357', example: 'XXXXXXXX' },
  { code: 'CZ', name: 'Czech Republic', dialCode: '+420', example: 'XXXXXXXXX' },
  { code: 'DJ', name: 'Djibouti', dialCode: '+253', example: 'XXXXXXXX' },
  { code: 'DO', name: 'Dominican Republic', dialCode: '+1', example: 'XXXXXXXXXX' },
  { code: 'EC', name: 'Ecuador', dialCode: '+593', example: 'XXXXXXXXX' },
  { code: 'SV', name: 'El Salvador', dialCode: '+503', example: 'XXXXXXXX' },
  { code: 'GQ', name: 'Equatorial Guinea', dialCode: '+240', example: 'XXXXXXXXX' },
  { code: 'ER', name: 'Eritrea', dialCode: '+291', example: 'XXXXXXX' },
  { code: 'EE', name: 'Estonia', dialCode: '+372', example: 'XXXXXXXX' },
  { code: 'ET', name: 'Ethiopia', dialCode: '+251', example: 'XXXXXXXXX' },
  { code: 'FJ', name: 'Fiji', dialCode: '+679', example: 'XXXXXXX' },
  { code: 'GA', name: 'Gabon', dialCode: '+241', example: 'XXXXXXX' },
  { code: 'GM', name: 'Gambia', dialCode: '+220', example: 'XXXXXXX' },
  { code: 'GE', name: 'Georgia', dialCode: '+995', example: 'XXXXXXXXX' },
  { code: 'GH', name: 'Ghana', dialCode: '+233', example: 'XXXXXXXXX' },
  { code: 'GD', name: 'Grenada', dialCode: '+1', example: 'XXXXXXX' },
  { code: 'GT', name: 'Guatemala', dialCode: '+502', example: 'XXXXXXXX' },
  { code: 'GN', name: 'Guinea', dialCode: '+224', example: 'XXXXXXXXX' },
  { code: 'GW', name: 'Guinea-Bissau', dialCode: '+245', example: 'XXXXXXX' },
  { code: 'GY', name: 'Guyana', dialCode: '+592', example: 'XXXXXXX' },
  { code: 'HT', name: 'Haiti', dialCode: '+509', example: 'XXXXXXXX' },
  { code: 'HN', name: 'Honduras', dialCode: '+504', example: 'XXXXXXXX' },
  { code: 'HK', name: 'Hong Kong', dialCode: '+852', example: 'XXXXXXXX' },
  { code: 'HU', name: 'Hungary', dialCode: '+36', example: 'XXXXXXXXX' },
  { code: 'IS', name: 'Iceland', dialCode: '+354', example: 'XXXXXXX' },
  { code: 'IR', name: 'Iran', dialCode: '+98', example: 'XXXXXXXXXX' },
  { code: 'IL', name: 'Israel', dialCode: '+972', example: 'XXXXXXXXX' },
  { code: 'JM', name: 'Jamaica', dialCode: '+1', example: 'XXXXXXX' },
  { code: 'KZ', name: 'Kazakhstan', dialCode: '+7', example: 'XXXXXXXXXX' },
  { code: 'KE', name: 'Kenya', dialCode: '+254', example: 'XXXXXXXXX' },
  { code: 'KG', name: 'Kyrgyzstan', dialCode: '+996', example: 'XXXXXXXXX' },
  { code: 'LA', name: 'Laos', dialCode: '+856', example: 'XXXXXXXX' },
  { code: 'LV', name: 'Latvia', dialCode: '+371', example: 'XXXXXXXX' },
  { code: 'LS', name: 'Lesotho', dialCode: '+266', example: 'XXXXXXXX' },
  { code: 'LR', name: 'Liberia', dialCode: '+231', example: 'XXXXXXXX' },
  { code: 'LT', name: 'Lithuania', dialCode: '+370', example: 'XXXXXXXX' },
  { code: 'LU', name: 'Luxembourg', dialCode: '+352', example: 'XXXXXXXXX' },
  { code: 'MO', name: 'Macau', dialCode: '+853', example: 'XXXXXXXX' },
  { code: 'MK', name: 'Macedonia', dialCode: '+389', example: 'XXXXXXXX' },
  { code: 'MG', name: 'Madagascar', dialCode: '+261', example: 'XXXXXXXXX' },
  { code: 'MW', name: 'Malawi', dialCode: '+265', example: 'XXXXXXXXX' },
  { code: 'MV', name: 'Maldives', dialCode: '+960', example: 'XXXXXXX' },
  { code: 'ML', name: 'Mali', dialCode: '+223', example: 'XXXXXXXX' },
  { code: 'MT', name: 'Malta', dialCode: '+356', example: 'XXXXXXXX' },
  { code: 'MR', name: 'Mauritania', dialCode: '+222', example: 'XXXXXXXX' },
  { code: 'MU', name: 'Mauritius', dialCode: '+230', example: 'XXXXXXX' },
  { code: 'MD', name: 'Moldova', dialCode: '+373', example: 'XXXXXXXX' },
  { code: 'MN', name: 'Mongolia', dialCode: '+976', example: 'XXXXXXXX' },
  { code: 'ME', name: 'Montenegro', dialCode: '+382', example: 'XXXXXXXX' },
  { code: 'MZ', name: 'Mozambique', dialCode: '+258', example: 'XXXXXXXXX' },
  { code: 'MM', name: 'Myanmar', dialCode: '+95', example: 'XXXXXXXXX' },
  { code: 'NA', name: 'Namibia', dialCode: '+264', example: 'XXXXXXXX' },
  { code: 'NP', name: 'Nepal', dialCode: '+977', example: 'XXXXXXXXX' },
  { code: 'NI', name: 'Nicaragua', dialCode: '+505', example: 'XXXXXXXX' },
  { code: 'NE', name: 'Niger', dialCode: '+227', example: 'XXXXXXXX' },
  { code: 'PA', name: 'Panama', dialCode: '+507', example: 'XXXXXXXX' },
  { code: 'PY', name: 'Paraguay', dialCode: '+595', example: 'XXXXXXXXX' },
  { code: 'PE', name: 'Peru', dialCode: '+51', example: 'XXXXXXXXX' },
  { code: 'PL', name: 'Poland', dialCode: '+48', example: 'XXXXXXXXX' },
  { code: 'RO', name: 'Romania', dialCode: '+40', example: 'XXXXXXXXX' },
  { code: 'RW', name: 'Rwanda', dialCode: '+250', example: 'XXXXXXXXX' },
  { code: 'SN', name: 'Senegal', dialCode: '+221', example: 'XXXXXXXXX' },
  { code: 'RS', name: 'Serbia', dialCode: '+381', example: 'XXXXXXXXX' },
  { code: 'SL', name: 'Sierra Leone', dialCode: '+232', example: 'XXXXXXXX' },
  { code: 'SG', name: 'Singapore', dialCode: '+65', example: 'XXXXXXXX' },
  { code: 'SK', name: 'Slovakia', dialCode: '+421', example: 'XXXXXXXXX' },
  { code: 'SI', name: 'Slovenia', dialCode: '+386', example: 'XXXXXXXX' },
  { code: 'LK', name: 'Sri Lanka', dialCode: '+94', example: 'XXXXXXXXX' },
  { code: 'TZ', name: 'Tanzania', dialCode: '+255', example: 'XXXXXXXXX' },
  { code: 'TG', name: 'Togo', dialCode: '+228', example: 'XXXXXXXX' },
  { code: 'UG', name: 'Uganda', dialCode: '+256', example: 'XXXXXXXXX' },
  { code: 'UA', name: 'Ukraine', dialCode: '+380', example: 'XXXXXXXXX' },
  { code: 'UY', name: 'Uruguay', dialCode: '+598', example: 'XXXXXXXX' },
  { code: 'UZ', name: 'Uzbekistan', dialCode: '+998', example: 'XXXXXXXXX' },
  { code: 'VE', name: 'Venezuela', dialCode: '+58', example: 'XXXXXXXXXX' },
  { code: 'ZM', name: 'Zambia', dialCode: '+260', example: 'XXXXXXXXX' },
  { code: 'ZW', name: 'Zimbabwe', dialCode: '+263', example: 'XXXXXXXXX' },
];
